# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_about_dialog(object):
    def setupUi(self, about_dialog):
        about_dialog.setObjectName("about_dialog")
        about_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        about_dialog.resize(400, 331)
        about_dialog.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/images/passkey.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        about_dialog.setWindowIcon(icon)
        about_dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(about_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ablout_label = QtWidgets.QLabel(about_dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ablout_label.setFont(font)
        self.ablout_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ablout_label.setObjectName("ablout_label")
        self.verticalLayout.addWidget(self.ablout_label)
        self.about_field = QtWidgets.QTextBrowser(about_dialog)
        self.about_field.setFocusPolicy(QtCore.Qt.NoFocus)
        self.about_field.setAutoFillBackground(False)
        self.about_field.setStyleSheet("background: rgba(0, 255, 0, 0)")
        self.about_field.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.about_field.setObjectName("about_field")
        self.verticalLayout.addWidget(self.about_field)
        self.cryptex_image = QtWidgets.QLabel(about_dialog)
        self.cryptex_image.setText("")
        self.cryptex_image.setPixmap(QtGui.QPixmap("ui/images/cryptex.png"))
        self.cryptex_image.setAlignment(QtCore.Qt.AlignCenter)
        self.cryptex_image.setObjectName("cryptex_image")
        self.verticalLayout.addWidget(self.cryptex_image)
        self.author_label = QtWidgets.QLabel(about_dialog)
        self.author_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.author_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.author_label.setObjectName("author_label")
        self.verticalLayout.addWidget(self.author_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_button = QtWidgets.QPushButton(about_dialog)
        self.close_button.setMaximumSize(QtCore.QSize(75, 16777215))
        self.close_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.close_button.setAutoFillBackground(False)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(about_dialog)
        QtCore.QMetaObject.connectSlotsByName(about_dialog)

    def retranslateUi(self, about_dialog):
        _translate = QtCore.QCoreApplication.translate
        about_dialog.setWindowTitle(_translate("about_dialog", "About..."))
        self.ablout_label.setText(_translate("about_dialog", "CryptEX"))
        self.about_field.setPlaceholderText(_translate("about_dialog", "Blah-blah-blah~"))
        self.author_label.setText(_translate("about_dialog", "Author"))
        self.close_button.setText(_translate("about_dialog", "Close"))
